### ISSUE TITLE
Bug in UI on homepage

### ISSUE THREAD

**Issue by apanjain** [rohitjha941/SMP#107]
Upon switching between different tabs, the `Learn More button` on the home screen (meant for mobile version) pops up along with the text link `Learn More >`

**Comment by apanjain** [comment]
![Screenshot from 2020-12-22 20-54-57](https://user-images.githubusercontent.com/51409512/102905001-890d4c80-4498-11eb-97c7-10099ead3917.png)

**Comment by Jwright707** [comment]
I would like to tackle this issue
