### ISSUE TITLE
HTML based content

### ISSUE THREAD

**Issue by hacksdump** [rohitjha941/SMP#43]
In frontend, the HTML content is rendered as:
```js
var textedited = (el.getElementsByTagName("p")[0].innerHTML+el.getElementsByTagName("p")[1].innerHTML+el.getElementsByTagName("p")[2].innerHTML).substr(0,blogCardContentCharacterLimit).trim()
```
in the file `src/components/BlogCard/index.js`.
But if the content does not have 3 paragraphs, frontend breaks due to out of bounds access.
We should rather move to JSON based content in the backend and write the render logic on the frontend.
For example, the content can be sent as an array and the individual array elements can be rendered  as a paragraph.

**Comment by apanjain** [comment]
thats fixed up already in  one of the prs

**Comment by apanjain** [comment]
Html is fine , it provides support for bold characters as well

**Comment by hacksdump** [comment]
Well keep HTML in favour of formatting. Other forms will require explicit parsing. I'll close this issue.
