### ISSUE TITLE
Fix active router link highlight color.

### ISSUE THREAD

**Issue by hacksdump** [rohitjha941/SMP#55]
The route component (partial)
```jsx
<NavLink activeClassName="active-route">
```

**Comment by apanjain** [comment]
@hacksdump what exactly is that we need to do here?

**Comment by hacksdump** [comment]
In the top navbar where we have "Blogs", "Events" the current button/navitem should be highlighted. This issue is low priority, but the highlighting helps to know which page I am on.
Something like this where the gallery button is highlighted. Ours will be more subtle like just an underline.

[https://i1.wp.com/onaircode.com/wp-content/uploads/2019/09/a-navigation-bar-dropdown-menu.jpg?resize=1080%2C675&ssl=1](https://i1.wp.com/onaircode.com/wp-content/uploads/2019/09/a-navigation-bar-dropdown-menu.jpg?resize=1080%2C675&ssl=1)
