### ISSUE TITLE
Thumbnail not in the desired aspect ratio(needs to be addressed)

### ISSUE THREAD

**Issue by CapTen101** [rohitjha941/SMP#84]
- Here, the image is in a 4:3 phone clicked format. After cropping the image, it looks a Lil' bit weird
![image](https://user-images.githubusercontent.com/45699327/81808610-93985880-953d-11ea-9a8c-d54c21848efb.png)

**Comment by apanjain** [comment]
I have set default aspect ratio to 16:9, upload future images cropped accordingly..

**Comment by CapTen101** [comment]
Alright, cool👍
